description: "PowerLite PDO - Effortless Database Interactions: Explore our comprehensive documentation to learn how Power Lite PDO simplifies your PHP database interactions."

doc_version: "1.0.0"

arguments_code_class: "text-warning-emphasis bg-secondary-subtle mb-0"

code_block_panel:
    max_lines: 50

hb:
  # override SASS variables, please replace the dash with underline, e.g. `list-group-color` should be `list_group_color`.
  # styles:
  #   primary: '#6610f2'

  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.

  full_width: false # when true, the layout takes full width globally.

  google_fonts:
    families:
      - name: Roboto

  header:
    brand: '' # the brand name, leave it empty to use site's title.
    logo: '/images/powerlite-pdo-logo-horizontal-small.png'
    logo_bg: '#ffffff' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    git_repo:
      name: 'power-lite-pdo'
      owner: 'migliori'
      service: 'github'
    socials:
      github: migliori
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: migliori
  # terms:
  #   # the paginate for categories, tags, series list pages.
  #   paginate: 12
  # docs:
  #   giscus:
  #     repo: hbstack/theme
  #     repo_id: R_kgDOJP3qtA
  #     category_id: DIC_kwDOJP3qtM4CVavM
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: migliori/power-lite-pdo
      branch: main
      # subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/powerlite-pdo-logo.png
# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#edeae2'
    theme_color: '#edeae2'
    short_name: 'PowerLite PDO'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

# mermaid:
#   # replace it with other CDNs or self-hosted URLs.
#   js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

# hugopress:
#   modules:
#     hb-custom:
#       hooks:
#         # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
#         head-end:
#           cacheable: true
#         # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
#         body-end:
#           cacheable: true
